### ISSUE TITLE
Use the kube-arango operator

### ISSUE THREAD

**Issue by sleepycat** [cds-snc/report-a-cybercrime#485]
The current database setup is very manual, and currently runs a single instance of Arango.
ArangoDB provides an [operator](https://operatorhub.io/what-is-an-operator) called [kube-arango](https://github.com/arangodb/kube-arangodb) which we should use instead of our existing homebrew setup.

There is a little [initial setup](https://github.com/arangodb/kube-arangodb#installation-of-latest-release-using-kubectl), and then we will need to define an [ArangoDeployment](https://www.arangodb.com/docs/devel/deployment-kubernetes-deployment-resource.html?origin_team=T07NV0TD4#arangodeployment-custom-resource) object for the operator to action. As a starting point:
```yaml
apiVersion: "database.arangodb.com/v1alpha"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
spec:
  image: 3.4.7
  environment: production
  mode: Single
  tls:
    caSecretName: None
  sync:
    externalAccess:
      type: None
````
One noteworthy difference between our current setup (which uses the [docker image](https://hub.docker.com/_/arangodb#choosing-an-authentication-method) directly) and the operator is that we are able to pass in credentials, and that is [not currently possible](https://github.com/arangodb/kube-arangodb/issues/319#issuecomment-451141023) with the operator.
